package View;

import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;


public class ProductsDisplay extends javax.swing.JPanel {


    
    ArrayList<ProductView> refgProducts;

    /**
     *
     */
    public JPanel pnlProducts;
    
    /**
     *
     * @param products
     */
    public ProductsDisplay(ArrayList<ProductView> products) {
        refgProducts=products;
        pnlProducts=new JPanel(new GridLayout(products.size()/4, 4,10,10));
        initComponents();
         
        for(int i=0;i<products.size();i++){
          pnlProducts.add(refgProducts.get(i));
        } 
        scrollProducts.setViewportView(pnlProducts);
         
    }
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scrollProducts = new javax.swing.JScrollPane();

        setPreferredSize(new java.awt.Dimension(819, 446));
        setLayout(new java.awt.GridBagLayout());

        scrollProducts.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollProducts.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 791;
        gridBagConstraints.ipady = 428;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        add(scrollProducts, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @return
     */
    public JScrollPane getScrollProducts() {
        return scrollProducts;
    }

    /**
     * Creates new form ProductsDisplay
     * @param scrollProducts
     */
    public void setScrollProducts(JScrollPane scrollProducts) {
        this.scrollProducts = scrollProducts;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollProducts;
    // End of variables declaration//GEN-END:variables
}
